language: python
install: "pip install nose pylint"
python:
  - "3.5"
  - "3.6"
script: "nosetests && pylint -E -j 6 bot.py commands/configuration.py commands/nsfw.py commands/weather.py commands/music.py commands/information.py commands/moderation.py commands/fuckery.py utils/buildinfo.py"
before_install:
  - git clone https://github.com/Rapptz/discord.py
  - cd discord.py
  - python -m pip install -U .[voice]
  - cd ..
  - pip install wikipedia darkskylib geocoder pyping stdlib youtube_dl forecastiopy zipfile codecs postgres asyncqlio colorlog
